server:
  port: 8761 # Eureka'nın çalıştığı port

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # Kendisini kayıt etmesin
    fetch-registry: false       # Kayıt defterini çekmesin
    service-url:
      defaultZone: http://localhost:8761/eureka/