server:
  port: 8080

spring:
  application:
    name: api-gateway

  # --- 1. GÜVENLİK (KEYCLOAK) ---
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/ecommerce-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: 7qH8b8TS5cbkEYtXxjA58ZHMrebsy4LF
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email, roles
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/ecommerce-realm/protocol/openid-connect/certs

  # --- 2. GATEWAY & LOADBALANCER ---
  cloud:
    # LoadBalancer Performansı için Caffeine Cache (Logdaki uyarıyı çözer)
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=10,maximumSize=500,expireAfterWrite=5m

    gateway:
      # Tüm servislere JWT Token'ı otomatik ilet
      default-filters:
        - TokenRelay

      # --- ROTA TANIMLARI ---
      routes:
        # 1. PRODUCT SERVICE
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**, /api/v1/brands/**
          filters:
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallback/product

        # 2. USER SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback/user

        # 3. SEARCH SERVICE
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/v1/search/**
          filters:
            - name: CircuitBreaker
              args:
                name: searchCircuitBreaker
                fallbackUri: forward:/fallback/search

        # 4. ORDER SERVICE
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/order

        # 5. PAYMENT SERVICE
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/fallback/payment

        # 6. RECOMMENDATION SERVICE
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/recommendations/**
          filters:
            - name: CircuitBreaker
              args:
                name: recommendationCircuitBreaker
                fallbackUri: forward:/fallback/recommendation

        # 7. NOTIFICATION SERVICE
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationCircuitBreaker
                fallbackUri: forward:/fallback/notification

        # 8. FEEDBACK SERVICE
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/api/feedbacks/**
          filters:
            - name: CircuitBreaker
              args:
                name: feedbackCircuitBreaker
                fallbackUri: forward:/fallback/feedback

# --- 3. EUREKA CLIENT ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# --- 4. RESILIENCE4J (HATA TOLERANSI) ---
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      productCircuitBreaker:
        baseConfig: default
      userCircuitBreaker:
        baseConfig: default
      searchCircuitBreaker:
        baseConfig: default
      orderCircuitBreaker:
        baseConfig: default
      paymentCircuitBreaker:
        baseConfig: default
      recommendationCircuitBreaker:
        baseConfig: default
      notificationCircuitBreaker:
        baseConfig: default
      feedbackCircuitBreaker:
        baseConfig: default