server:
  port: 8080

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery.locator.enabled: true # Servis isimleriyle yönlendirmeye izin ver
      routes:
        - id: auth_route
          uri: lb://AuthService # AUTH-SERVICE'e yönlendir
          predicates:
            - Path=/api/auth/**
        - id: profile_route
          uri: lb://UserProfileService # USER-PROFILE-SERVICE'e yönlendir
          predicates:
            - Path=/api/profile/**
          filters:
            - TokenRelay= # Gelen JWT'yi iç servise ilet
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak'tan RSA Public Key'in alındığı adres (8180 Portu)
          jwk-set-uri: http://localhost:8180/realms/my-realm/protocol/openid-connect/certs
          # JWT'yi imzalayan otoritenin (Issuer) adresi
          issuer-uri: http://localhost:8180/realms/my-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/