server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Eraycann/Microservice-E-Commerce-Config-Server"
          default-label: "main"
          skip-ssl-validation: true
          username: "Eraycann"
          password: ${GIT_KEY}