server:
  port: 8093

spring:
  application:
    name: search-service

  # --- ELASTICSEARCH AYARLARI ---
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 3s
    # Şifresiz modda çalıştığımız için username/password gerekmez

  # --- RABBITMQ AYARLARI ---
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# --- SERVICE DISCOVERY (EUREKA) ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# --- LOGLAMA (DEBUG) ---
logging:
  level:
    # Elasticsearch'e giden/gelen ham HTTP trafiğini (JSON) görmek için:
    org.springframework.data.elasticsearch.client.WIRE: TRACE
    # Spring Data işlemlerini ve sorgu oluşturma süreçlerini görmek için:
    org.springframework.data.elasticsearch.core: DEBUG